# Prometheus Configuration for FeastFrenzy

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'feastfrenzy-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FeastFrenzy Backend API
  - job_name: 'feastfrenzy-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # FeastFrenzy Frontend (if exposing metrics)
  - job_name: 'feastfrenzy-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # MySQL Exporter for database metrics
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Nginx Exporter for web server metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Redis Exporter for cache metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Custom application health checks
  - job_name: 'feastfrenzy-health'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/health'
    scrape_interval: 10s
    scrape_timeout: 5s